export const covid = [{
        day: 'Day 1:',
        context: 'I went to bed with a slight sore throat, but didn’t think much of it.  I was vaping a lot that evening so it wouldn’t be uncommon if my throat had been compromised from it.  I went to bed without a second thought with confidence that tomorrow would be better.'
    },
    {
        day: 'Day 2:',
        context: 'My throat was still a bit messed up from the night before.  Not like this anyways.  As the day progressed I noticed a small cough developing.  I ate a rather large meal consisting of some Korean food my mother sent, followed by a food coma that would render me unconscious for the rest of the evening.'
    },
    {
        day: 'Day 3:',
        context: 'It was morning.  I was still tired, and my appetite felt as though it had left me.  My throat still hurts.  “Okay, I’m sick.”  I thought to myself.  The acute cough has now turned into a perpetual cough.  Was it COVID?  No probably not, I only have a sore throat.  No fever, stools look fine, and I’m not having any other symptoms.  I’m not very hungry, but I can still eat.  I should eat.  I continue eating leftovers sent from my mother, and take a long bath. It’s dark, and I’m wet.  I’d fallen asleep in the bathtub with the lights off.  The water was a bit cold now.  I turn on the shower and finish cleaning myself off.  When looking at my phone I noticed I had a bunch of missed dm’s, I didn’t even feel like trying to reply.  I crawl into bed and try to sleep again.  I slept for a bit.'
    },
    {
        day: 'Day 4:',
        context: 'Three a.m, my cough is bad.  Text mom, I’m really sick, I can’t make it home today.  I feel fatigued now.  I turn on the tv to take my mind off of COVID.  I’m afraid now, afraid that I have COVID.  I don’t have any of the other symptoms, I’m probably fine.  I laid in bed coughing and eating random food while laying on my side.  I still needed to eat. Now there’s crumbs in my bed, I hate crumbs.  Twelve p.m, I’m still awake, mom calls to check on me.  Sister and mom convinced me to drive home to pick up my sister and take her home.  My sister is pregnant.  I didn’t think it’s a good idea, but agreed to be home the next day.  I fell asleep shortly after the phone call.'
    },
    {
        day: 'Day 5:',
        context: 'It’s two a.m.  I woke up shivering.  An uncontrollable shiver, and it’s cold.  My teeth are chattering, and I’m wrapped in a blanket covering my head.  The cold air burned my lungs as if I were breathing in liquid nitrogen.  I can’t sleep.  I grab my phone and increase the temperature on my thermostat.  I’m coughing again, and I can’t stop now.  Water, I need to drink plenty of water.  I filled two glasses of water and drank them both.  I laid back down thinking this can’t be COVID can it?  I can’t sleep again, my legs feel sore.'
    },
    {
        day: 'Day 6',
        context: 'Six a.m, I need to leave in 4 hours to pick up my sister.  I just need a few hours of… sleep.  My phone’s ringing, it’s a recruiter.  “Hello, this is JR… Yes I can answer a few questions.”  I answered groggily.  I finally hung up the phone with the job recruiter.  Crap, I’m late.  I need to go get my sister.  My cough is back, my legs feel a little tender, but my chills are gone.  I grab my mask to protect others from myself.  I get in my car and two hours later I arrive at my mom’s house.  I don’t go near my family, I don’t want to risk getting them sick.  I have my mask on in my mom’s home.  She asks if she can hug me.  I tell her no, stay away from me.  As if I was some sort of plagued animal.  My sister wipes down the interior of my car, and offers to drive.  I agree to let her drive, and sit in the back seat with my mask on.  An hour later, we arrived at her home.  She gets out while I switch to the front seat.  I’m feeling tired, really tired.  Another hour, and I would be home.  Finally, home at last.  Kicked off my shoes and fell into my sheets.  My eyes are heavy.  It’s time to sleep again.'
    },
    {
        day: 'Day 6:',
        context: 'Five a.m.  “Oh god…”  I rushed to the bathroom.  There was nothing solid about my stool.  My legs felt like jello, my breathing felt short, and my head was pounding, and I was coughing uncontrollably.  My bathroom was cold, and my chills were back.  After sitting on the toilet for a while, I realized my muscles ache… everywhere.  It hurt to look left and right, my eyeball muscles were affected as well.  “It’s COVID, it’s gotta be…”  I thought to myself.  I stood up almost falling back over.  I was fatigued, and my legs fell asleep.  I was sitting there for a while.  I poured myself water, and started taking vitamins.  I heated up some random food and began to eat. I wasn’t hungry, but I knew I needed to force myself.  I laid in bed in the fetal position scooping food into my mouth from my side.  It wasn’t pretty, nor a good idea, but I didn’t have the energy to sit up and eat properly.  I shoved the remaining bowl of food into my headboard cupboard.  I couldn’t eat anymore.  I downed a bunch of water and covered back up into my blanket.  The aching pain was unreal, I’d never experienced this before during the flu or any other illnesses.  I eventually fell asleep again after 5 or 6 hours.'
    },
    {
        day: 'Day: 7',
        context: 'Fourteen hours later it’s 1:00 a.m.  My sleeping schedule is completely backwards.  It’s hard for me to stand without feeling dizzy.  “Happy 4th of July…” I thought to myself.  My cough was gone, and I didn’t really have a sore throat.  I didn’t have the energy to move around however.  I forced myself to eat again.  I sat down in my chair this time.  Aside from my migraine, my body didn’t feel strong enough to fight off gravity.  I was struggling to keep my body sitting upright.  My muscles were aching all over.  When I stood up, I could feel my feet dragging against the hardwood floors.  "This is what zombies must feel like,"  I thought to myself--trying to make light of things.  I felt dazed, and couldn’t think properly.  I still needed to find a job.  I started to feel a lot of stress.  The combination of feeling horrible, and having real life responsibilities being unattended made me feel a rush of anxiety.  I felt confused, I tried to recall some basic programming logic and couldn’t make sense of it.  Before the second wave of stress could hit me I fell asleep.  There he was, a programming friend of mine. Sitting on my countertop with his feet dangling down.  I could see him from my bed, and I was still incapacitated.  “I can’t get up,” I said to my friend.  “Come sign this paperwork if you want this job,”  He replied.  I literally couldn’t get up.  Why was he doing this to me?  I’m sweating, and it’s pitch black.  It was a dream.  It’s 11:30 p.m.  I still feel terrible, well, less terrible than earlier, terrible nonetheless.  I chopped up some kimchi and tossed it into a pot with water.  Added some soy sauce, daeng jjon sauce, and shrimp.  A shrimp kimchi soup would probably make me feel better.  I look in my rice pot, the rice is a bit old.  I wasn’t about to wait.  I ate the rice along with the kimchi soup.  I felt a bit better.  I sat up and felt less fatigued than earlier.  I popped some tylenol, vitamins, and drank a few glasses of water.  Something was off but everything has been awful so I didn’t think too much about it.  I laid back down, time to sleep again.'
    },
    {
        day: 'Day 8:',
        context: 'I felt a bit refreshed.  I didn’t feel like my feet were dragging as badly.  The muscle aches were less painful, but the migraine was still prevalent.  My eyes, good lord, my eyes.  It was like lifting and being sore and then trying to use that same muscle group two days later.  Except this was my eyes.  This was indeed one of the strangest experiences in my life, and it didn’t feel good.  Again, my stool wasn’t solid, maybe it’s because I’d been eating nothing but soup?  Probably not.  My apartment was dark, and helped with my headaches.  I felt alone, like I hadn’t really spoken with anyone for quite some time.  I hadn’t, not with my voice.I started brushing my teeth and there was a tingling sensation on my tongue.  I must’ve burnt it on the soup.  I spoke out loud while brushing my teeth while looking at myself in the mirror, “You should be more careful next time.”  It was the first few words I’d spok en in a few days.  I felt a little weird talking to myself, but I needed to be sure I could even speak still.  I started thinking anything can happen at this point.Kimchi soup, I was eating a lot of it.  It’s packed with vitamins and is considered a superfood.  I thought that a soup version of this was probably one of the best options for me to eat.  I was getting sick of it however.  It was starting to taste really bad.  “Wait, does it taste bad?” I took another bite.  I couldn’t taste anything, I could only feel the spice.  I leaned over the soup and tried to take a deep smell.  Kimchi soup has a strong sour smell to it, in which I could not smell anything either.  I ran over to my bathroom and sprayed cologne into the air, nope no smell. I got on my grocery app and started ordering food.  Particularly snacks.  Any sort of snack from salty, spicy, sweet, any and all kinds of flavors.  Along with some necessary items, orange juice, fruit, veggies, meat, etc.  I went to bed feeling a bit afraid my taste would never come back.'
    },
    {
        day: 'Day 9:',
        context: 'I woke up feeling better than any other day.  My cough was pretty much gone.  My sore throat was non-existent.  My nose was a bit runny, and the muscle aches had dissipated a lot.  I hadn’t gotten a chill since the day before.  I still couldn’t smell or taste, but I would get groceries to see what I could and couldn’t taste.  My stools were semi solid.  This was exciting.  Things seemed to have started to get better.  I didn’t feel like I was going to collapse and I would have a bunch of snacks to eat there shortly. I love snacks, and I was feeling hungry.  I grabbed my mask and headed out.  I pulled up to the pickup area, and popped my trunk and awaited for my groceries to be loaded into my vehicle.  There were some discrepancies on the grocery substitutes, but I thought to myself, “yenno what, it’s pretty much all there, let’s just go home.”  The only part that bothered me was that they replaced a bag of oranges with a single orange.  Not sure how that is even comparable, but I had everything else.  After putting most of the groceries away, I had a table laid out full of different snacks.  Oreos, Nutter Butters, Flaming hot cheetos, ice cream, and of course a glass of orange juice.  I took a drink out of the orange juice.  Nothing.  I couldn’t taste anything.  I started taking a bite out of everything and I couldn’t taste a single thing.  Imagine eating something with all the right textures and none of the flavor.  It was very strange and scary.  I opened my dms and started to reply to people of my experience.  It was exhausting.  I explained to everyone that I would write an article that would describe my experience.  After eating tons of tasteless food, I laid down in my bed and started typing this out.  Shortly after wrapping up the Day 9 entry, I rolled over to my side and started watching a random show.  It was late and my sleeping schedule was backwards.  Still I had to try to sleep.  I wasn’t feeling well, but at that point it felt like a normal flu, which is significantly better than COVID by the way.  As my eyes fell shut, I thought to myself, “I hope I can taste tomorrow.”'
    },
    {
        day: 'Day 10:',
        context: 'I slept, I mean I SLEPT.  I slept all day today.  For some reason my body was feeling fatigued.  The headache was gone, and I was able to move around pretty easily.  I still can’t taste anything.  Not being able to taste or smell food is very stressful.  My nose was runny again.  I wasn’t feeling good, but I definitely wasn’t feeling bad either.  I was feeling tired, and I’m unsure if this is some sort of relapse of COVID that I was hearing about.  There are some recurring effects until COVID fully takes its course.  My throat wasn’t in pain anymore, but there is a feeling in my lungs, like fluids that shouldn’t be there.'
    },
]

export default covid